### ISSUE TITLE
Clase conexion

### ISSUE THREAD

**Issue by falasias** [ISWPOLI/Intencion-Horaria#32]
Conectar la base de datos al proyecto de logeo #24 

**tareas : **
+ [x] Crear nuestra clase de conexión 
+ [x] Implementar lo investigado en la creación de la conexión y las búsquedas
+ [x] Verificar el funcionamiento
